version: "3.8"

services:
  backend:
    image: abdulraheem02/finalexam-backend:latest
    container_name: staging-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: 5000
      NODE_ENV: staging
    networks:
      - staging-network

  frontend:
    image: abdulraheem02/finalexam-frontend:latest
    container_name: staging-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - staging-network

networks:
  staging-network:
    driver: bridge

