version: "3.8"

services:
  backend:
    build:
      context: ./backendsample
      dockerfile: Dockerfile
    image: abdulraheem02/finalexam-backend:latest
    container_name: devops-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backendsample/.env
    environment:
      PORT: 5000
    networks:
      - devops-network

  frontend:
    build:
      context: ./frontendsample
      dockerfile: Dockerfile
    image: abdulraheem02/finalexam-frontend:latest
    container_name: devops-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge
